name: Sync Fork 17

on:
  schedule:
    - cron: '0 0 * * 0'  # Exécute le workflow tous les dimanches à minuit
  workflow_dispatch:  # Permet de déclencher manuellement le workflow si besoin

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Clone tout l'historique
          fetch: all     # Télécharge toutes les branches
          persist-credentials: false  # Désactive les credentials par défaut
     
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      
      - name: Configure Git user
        run: |
          git config --local user.email "no-reply-dev@jlddesign.ch"
          git config --local user.name "Bot JLD"
          
      - name: Add upstream repository
        run: |
          run: git remote add upstream https://github.com/odoo/odoo.git
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}

      - name: Sync branch with upstream
        run: gh repo sync JLDdesign/odoo_odoo -b 17.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}

